import React, { useContext } from 'react'
import { getSession, useSession } from 'next-auth/react'
import Login from '../components/Login'

import Head from 'next/head'
import { useRouter } from 'next/router'
import { AppContext } from '../context/AppContext'
import Modal from '@/components/Modal'
import Sidebar from '@/components/Sidebar'
import SinglePost from '@/components/SinglePost'


const PostPage = () => {
    const { data: session } = useSession()
    const [appContext] = useContext(AppContext)
  
    if (!session) return <Login />
  return (
    <div>
         <Head>
        <title>Tweets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='relative max-w-[1400px] mx-auto'>
        <Sidebar/>
       
        <div className='flex gap-6'>
           <SinglePost/>
        {appContext?.isModalOpen && <Modal/>}
        </div>
      </main>
    </div>
  )
}

export default PostPage