import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getSession, useSession } from 'next-auth/react'
import Login from '@/components/Login'
import Sidebar from '@/components/Sidebar'
import Feed from '@/components/Feed'
import { useContext } from 'react'
import { AppContext } from '../context/AppContext'
import Modal from '@/components/Modal'
import Widgets from '@/components/Widgets'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { data: session } = useSession()
  const [appContext] = useContext(AppContext)

  if (!session) return <Login />
  return (
    <>
     <div>
      <Head>
        <title>Twitter-2.O</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='relative max-w-[1400px] mx-auto'>
        <Sidebar/>
        <div className='flex gap-6'>
          <Feed/>
          <Widgets/>
          
          {appContext?.isModalOpen && <Modal/>}
        </div>
      </main>

    </div>
    </>
  )
}
